version: '3.7'

services:
  mongo:
    image: mongo:6.0.13-jammy
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - prose_dbdata:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: db_user
      MONGO_INITDB_ROOT_PASSWORD: db_pwd

  
  mongo-express:
    image: mongo-express:1.0.2-20-alpine3.19
    restart: always
    depends_on:
      - mongo
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: db_user
      ME_CONFIG_MONGODB_ADMINPASSWORD: db_pwd
      ME_CONFIG_MONGODB_URL: mongodb://db_user:db_pwd@mongo:27017/

  phaven-api:
    build: .
    restart: always
    depends_on:
      - mongo
    ports:
      - 8000:8000
    environment:
      MONGO_URI: mongodb://db_user:db_pwd@mongo:27017/
      SECRET_KEY:
      ALGORITHM: HS256
      ACCESS_TOKEN_EXPIRE_DAYS:
      RESET_PASSWORD_URL:
      VERIFY_EMAIL_URL:
      EMAIL_ACCOUNT:
      EMAIL_PASSWORD:
      SMTP_HOST:
      SMTP_PORT:

volumes:
  prose_dbdata: